### ISSUE TITLE
Input_file and superpixel file

### ISSUE THREAD

**Issue by zhangchbin** [tarun005/UDOS#1]
Hi, thanks for your sharing. The first issue is that the args ```--input_file``` is required for generating superpixel annotation file with SS, but I don't know what it is, not ```annotations/instances_train_2017.json```. The second issue is that the program needs MCG json file not SS file, when I run the training script for VOC-to-NonVOC with downloaded SS json file. Thank you.

**Comment by tarun005** [comment]
Both of them should be fixed in the latest commit. Please let us know if it isn't.
